# Generated by Django 5.2.7 on 2025-11-02 17:47

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Source',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('base_url', models.URLField()),
                ('api_path', models.CharField(default='/package_search', max_length=200)),
                ('active', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='Tag',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='HarvestJob',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('query', models.TextField()),
                ('started_at', models.DateTimeField(auto_now_add=True)),
                ('ended_at', models.DateTimeField(blank=True, null=True)),
                ('status', models.CharField(choices=[('P', 'Pending'), ('R', 'Running'), ('S', 'Success'), ('F', 'Failed')], default='P', max_length=1)),
                ('found', models.IntegerField(default=0)),
                ('imported', models.IntegerField(default=0)),
                ('error', models.TextField(blank=True)),
                ('source', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='jobs', to='harvest.source')),
            ],
        ),
        migrations.CreateModel(
            name='Dataset',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ckan_id', models.CharField(db_index=True, max_length=200)),
                ('name', models.CharField(max_length=255)),
                ('title', models.CharField(blank=True, max_length=500)),
                ('notes', models.TextField(blank=True)),
                ('org', models.CharField(blank=True, max_length=255)),
                ('license', models.CharField(blank=True, max_length=200)),
                ('spatial', models.CharField(blank=True, max_length=500)),
                ('temporal_start', models.DateField(blank=True, null=True)),
                ('temporal_end', models.DateField(blank=True, null=True)),
                ('last_modified', models.DateTimeField(blank=True, null=True)),
                ('url', models.URLField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('source', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='datasets', to='harvest.source')),
                ('tags', models.ManyToManyField(blank=True, to='harvest.tag')),
            ],
            options={
                'unique_together': {('source', 'ckan_id')},
            },
        ),
        migrations.CreateModel(
            name='Resource',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ckan_id', models.CharField(db_index=True, max_length=200)),
                ('name', models.CharField(blank=True, max_length=500)),
                ('format', models.CharField(blank=True, max_length=50)),
                ('url', models.URLField(blank=True)),
                ('last_modified', models.DateTimeField(blank=True, null=True)),
                ('size', models.BigIntegerField(blank=True, null=True)),
                ('dataset', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='resources', to='harvest.dataset')),
            ],
            options={
                'unique_together': {('dataset', 'ckan_id')},
            },
        ),
    ]
